### ISSUE TITLE
Notifications.java is broken 

### ISSUE THREAD

**Issue by VHUGO98** [martinmimigames/tiny-music-player#11]
Within the project, the "Notifications.java" file presents an import error in the code below:

import mg.utils.notify.NotificationHelper;

Would there be any correction?

**Comment by wmartinmimi** [comment]
in the project directory root, run:
```sh
git submodule init
git submodule update
```
this should get the missing code for mg.utils library

**Comment by VHUGO98** [comment]
> in the project directory root, run:
> 
> ```shell
> git submodule init
> git submodule update
> ```
> 
> this should get the missing code for mg.utils library

Thank you!
