### ISSUE TITLE
[Feature Request] Add a Pause and a Loop button please.

### ISSUE THREAD

**Issue by Mesum-Hussain** [martinmimigames/tiny-music-player#3]
Wonderful concept! I really love it! It just gets out of the way and lets me listen to my songs.

But the only thing holding me back from using it as my primary music player app is the lack of pause and loop functionality. If those are added, I will completely switch to this app for all my music needs.

**Comment by wmartinmimi** [comment]
Unless you are using an older android, the newer android would have the option to pause in the notification, although it might be hidden.

Hardware pause/play button should work on all android versions however. (eg. Bluetooth earphone buttons)

I will try to add the loop function, along with the notification pause button for older androids. It may take a while though.

Thank you for your appreciation and suggestions! :>

**Comment by wmartinmimi** [comment]
There was a bug where notification is not showning correctly on some devices, not sure if yours in one of them. This [new update (v1.2)](https://github.com/martinmimigames/tiny-music-player/releases/tag/v1.2) may fix it, although there is still only play/pause/close options.

**Comment by wmartinmimi** [comment]
Added loop button in the new version v1.3.
To download: 
- [Github release v1.3](https://github.com/martinmimigames/tiny-music-player/releases/tag/v1.3)
- [From the website](https://martinmimigames.github.io/projects/tiny-music-player/index.html)

F-droid version may take a while to update.

I hope this satisfy your needs. :>

I will close this issue after a few days if nothing else happens here, or you can close it if there is no problem.

**Comment by Mesum-Hussain** [comment]
> Added loop button in the new version v1.3.
> To download: 
> - [Github release v1.3](https://github.com/martinmimigames/tiny-music-player/releases/tag/v1.3)
> - [From the website](https://martinmimigames.github.io/projects/tiny-music-player/index.html)
> 
> F-droid version may take a while to update.
> 
> I hope this satisfy your needs. :>
> 
> I will close this issue after a few days if nothing else happens here, or you can close it if there is no problem.

Thanks! Working perfectly!
This is now officially the best Android music player out there.
🙂👍🏻
