### ISSUE TITLE
Sort order is not kept

### ISSUE THREAD

**Issue by hurzl** [martinmimigames/tiny-music-player#5]
On every start it is reset to "by name".

**Comment by wmartinmimi** [comment]
Sorry, I am not in control of the file explorer, and therefore unable to fix that.

Tiny Music Player does not contain a file explorer, but rather calls the ones you have installed on the device (including the system default). This is to reduce the size of the music player.

This means I do not have control over how the file explorer interacts with you, as it is not a part of Tiny Music Player. This including the presets it chooses.

You can instead ask the developer of the file explorer instead.

As such, I am unable fix the issue.
